#!/bin/sh
# Reuben Thomas 19th September 2022
# This code is in the public domain.

export WORD='[[:alpha:]]\+'
export NONSPACE='[[^:space:]]\+'
export ID='[[:alpha:]_]\+'
export TAG='<([a-zA-Z_:][a-zA-Z_:.0-9-]*)[\s>]'

grep-unique () {
    grep "$@" | sort | uniq
}

grep-frequency () {
    grep "$@" | sort | uniq -c | sort -n
}
